apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-configs
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: agentgateway-root
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OmerItach/agentgateway-infra.git
    path: k8s/overlays/dev
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
