apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: agentgateway-root
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    path: config/crd/standard
    targetRevision: v1.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
