apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-crds
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: agentgateway-root
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://kgateway-dev.github.io/charts
    chart: agentgateway-crds
    targetRevision: v2.2.0
    helm:
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
